### ISSUE TITLE
About training Codes

### ISSUE THREAD

**Issue by yy9568** [srihari-humbarwadi/Vehicle-Color-Recognition-using-Convolutional-Neural-Network#1]
Hi, Have you already trained on dataset? Thanks for your excellent job. @srihari-humbarwadi

**Comment by srihari-humbarwadi** [comment]
Yea I have trained it on a private dataset

**Comment by yy9568** [comment]
@srihari-humbarwadi  Well done! Bro. But I noticed that vehicle color dataset which mentioned in original paper, have you ever downloaded the dataset into your local device, I can't get dataset via url provided from paper.Thanks again.

**Comment by srihari-humbarwadi** [comment]
No I did not download the original dataset which the authors used in the paper. I guess it shouldn't be hard for you to scrape images yourself.
